- name: user-access
  src: https://github.com/cyberrangecz/ansible-role-user-access
  scm: git
  version: v1.0.0
- name: sandbox-logging
  src: https://github.com/cyberrangecz/ansible-role-sandbox-logging
  scm: git
  version: v1.0.0
- name: chrony
  src: https://github.com/cyberrangecz/ansible-role-chrony
  scm: git
  version: v1.0.0
- name: hosts-aliases
  src: https://github.com/cyberrangecz/ansible-role-hosts-aliases
  scm: git
  version: v1.0.0
